In [38]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/housedata/data.csv
/kaggle/input/housedata/output.csv
/kaggle/input/housedata/data.dat

In [39]:
import pandas as pd

housedata = pd.read_csv("../input/housedata/data.csv")

In [40]:
housedata.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [41]:
housedata.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [42]:
housedata= housedata.dropna(axis=0)

In [43]:
y = housedata.price

In [44]:
housefeatures = ['floors','sqft_living','sqft_lot']

In [45]:
x = housedata[housefeatures]

In [46]:
x.head()

   floors  sqft_living  sqft_lot
0     1.5         1340      7912
1     2.0         3650      9050
2     1.0         1930     11947
3     1.0         2000      8030
4     1.0         1940     10500

In [47]:
from sklearn.tree import DecisionTreeRegressor


housepricemodel = DecisionTreeRegressor(random_state=1)

housepricemodel.fit(x,y)

DecisionTreeRegressor(random_state=1)

In [50]:
print("Making predictions for the following 5 houses:")
print(x.head())
print("The predictions are")
print(housepricemodel.predict(x.head(30)))

Making predictions for the following 5 houses:
   floors  sqft_living  sqft_lot
0     1.5         1340      7912
1     2.0         3650      9050
2     1.0         1930     11947
3     1.0         2000      8030
4     1.0         1940     10500
The predictions are
[ 313000. 2384000.  342000.  420000.  550000.]